server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Redirigir errores de Nginx a stdout para Easypanel logs
    error_log /dev/stdout info;
    access_log /dev/stdout;
}
