server {
    listen 80;
    server_name _;

    root   /usr/share/nginx/html;
    index  index.html index.htm;

    # Acceso a logs para depuración
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Caché para activos estáticos (Vite genera hashes)
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    # Prevención de acceso a archivos ocultos
    location ~ /\. {
        deny all;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
